name: backendCIWorkflow
on:
  workflow_dispatch:
    paths:
      - 'backend/**'
    branches:       
      - main
        
  pull_request:
    paths:
      - 'backend/**'  
    branches: 
      - main
jobs:
  LINT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install depndencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install pipenv==2022.10.12
      - name: install project dependencies
        run: pipenv install --dev
      - name: run lint
        run: |
            cd starter/backend
            pipenv run lint
  TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies 
        run: |      
              python -m pip install --upgrade pip setuptools wheel        
              pip install pipenv==2022.10.12
      - name: install project dependencies
        run: pipenv install --dev         
      - name: run tests
        run: |
            cd starter/backend
            pipenv run test

  BUILD:
    needs: [LINT, TEST]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd starter/backend
          python -m pip install --upgrade pip setuptools wheel
          pip install pipenv
          pipenv install --dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: starter/backend
          file:  starter/backend/Dockerfile
          push: true
          tags: your-container-registry/your-image:latest