name: Backend Continuous deployment
on:
  workflow_dispatch:
  push:
    paths:
      - 'starter/backend/**'  
    branches: 
      - main   
jobs:
  LINT:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pipenv
    - name: Install project dependencies and flake8
      run: |
        cd starter/backend
        pipenv install --dev
        pipenv run pip install flake8
    - name: Run lint
      run: |
        cd starter/backend
        pipenv run flake8
  TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies 
        run: |      
              python -m pip install --upgrade pip setuptools wheel        
              pip install pipenv
      - name: install project dependencies and pytest
        run: |
            cd starter/backend
            pipenv install --dev         
            pipenv run pip install pytest      
      - name: run tests
        run: |
            cd starter/backend
            pipenv run test


  BUILD:
    needs: [LINT, TEST]
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: your-ecr-repo-name    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd starter/backend
          python -m pip install --upgrade pip setuptools wheel
          pip install pipenv
          pipenv install --dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1        

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: starter/backend
          file:  starter/backend/Dockerfile
          push: true
          tags: your-container-registry/your-image:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
       
       - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
         run: |
            docker build --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG starter/frontend
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
       with:
        version: 'latest'

      - name: updates the kubeconfig
        run: aws eks update-kubeconfig --name my-cluster-name

      - name: Set the image tag to the newer version    
        run: |
            cd starter/frontend/k8s
            kustomize edit set image frontend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Apply the manifests to the cluster
        run: kustomize build | kubectl apply -f -            